import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { GlobalProvider } from "@/context/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={inter.className}>
          <main className="relative">
            <section>
              <Navbar />
            </section>
            {children}
            <section className="padding bg-white-400">
              <Footer />
            </section>
          </main>
        </body>
      </GlobalProvider>
    </html>
  );
}
